---
- name: Replace default apache index.html
  hosts: Servers
  become: yes
  tasks:
    - name: Write 'Hello World from SJSU' to index.html
      command: bash -c 'echo "Hello World from SJSU" > /var/www/html/index.html'
